In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
# path = "E:/Documents/dtms69/67-018400.csv"
path = "D:/dtms69/dtms/dtms โหลดใหม่ ต.ค.-ธ.ค.68 ใช้ตัวนี้/67-018400.csv"

In [3]:
df = pd.read_csv(path, index_col=None)

In [4]:
df

,timestamp,dtmsid,C_A,C_B,C_C,F,HC_A,HC_B,HC_C,HV_A,...,S_A,S_B,S_C,S_TOT,TEMP_AMB,TEMP_TR,TEMP_OIL,V_A,V_B,V_C
0,2025-10-01T00:00:00,dtmsid1087,34.33,30.60,33.30,0.0,0.0,0.0,0.0,0.0,...,7.83,6.96,7.58,22.37,28.0,0.0,0.0,227.94,227.55,227.58
1,2025-10-01T00:05:00,dtmsid1087,30.77,27.99,30.85,0.0,0.0,0.0,0.0,0.0,...,7.05,6.40,7.05,20.50,28.0,0.0,0.0,228.96,228.55,228.54
2,2025-10-01T00:10:00,dtmsid1087,33.10,32.12,34.96,0.0,0.0,0.0,0.0,0.0,...,7.57,7.33,7.98,22.88,28.0,0.0,0.0,228.63,228.28,228.25
3,2025-10-01T00:15:00,dtmsid1087,29.93,29.71,30.99,0.0,0.0,0.0,0.0,0.0,...,6.85,6.79,7.08,20.72,28.0,0.0,0.0,228.82,228.58,228.55
4,2025-10-01T00:20:00,dtmsid1087,32.57,30.78,33.88,0.0,0.0,0.0,0.0,0.0,...,7.37,6.96,7.66,21.99,27.9,0.0,0.0,226.63,226.43,226.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25521,2025-12-30T23:40:00,dtmsid1087,22.48,25.74,25.26,0.0,0.0,0.0,0.0,0.0,...,5.23,5.95,5.87,17.05,24.0,0.0,0.0,232.52,231.28,232.46
25522,2025-12-30T23:45:00,dtmsid1087,20.27,23.47,23.56,0.0,0.0,0.0,0.0,0.0,...,4.71,5.43,5.47,15.61,24.0,0.0,0.0,232.36,231.31,232.29
25523,2025-12-30T23:50:00,dtmsid1087,20.17,23.38,23.68,0.0,0.0,0.0,0.0,0.0,...,4.69,5.41,5.50,15.60,24.3,0.0,0.0,232.54,231.33,232.35
25524,2025-12-30T23:55:00,dtmsid1087,18.88,21.95,22.67,0.0,0.0,0.0,0.0,0.0,...,4.39,5.08,5.27,14.74,24.6,0.0,0.0,232.35,231.23,232.26
25525,2025-12-31T00:00:00,dtmsid1087,20.51,22.90,23.47,0.0,0.0,0.0,0.0,0.0,...,4.78,5.30,5.46,15.54,24.5,0.0,0.0,232.89,231.62,232.75

In [5]:
df2 = df.copy()

In [6]:
print(df2['timestamp'].dtype)

object

In [7]:
df2['timestamp'] = pd.to_datetime(df2['timestamp'])

In [8]:
s = pd.to_datetime(df2['timestamp']).dropna().drop_duplicates().sort_values()

start = s.min().floor('5min')
end   = s.max().ceil('5min') - pd.Timedelta(minutes=5)  

full = pd.date_range(start, end, freq='5min')

In [9]:
day_count = pd.Series(s).groupby(pd.Series(s).dt.date).size()
incomplete_days = day_count[day_count < 384]
print(incomplete_days)

timestamp
2025-10-01    288
2025-10-02    287
2025-10-03    287
2025-10-04    287
2025-10-05    287
             ...
2025-12-27    287
2025-12-28    288
2025-12-29    287
2025-12-30    287
2025-12-31      1
Name: timestamp, Length: 92, dtype: int64

In [10]:
print(day_count.shape[0])

92

In [11]:
# ถ้า period ตรง 1 เดือนพอดี และคาดหวัง 384 จุด/วัน
expected = 384 * day_count.shape[0]         # คิดจากจำนวนวันจริงที่พบ
actual   = len(s)
print("expected:", expected, "actual:", actual, "missing:", expected - actual)

expected: 35328 actual: 25526 missing: 9802

In [ ]:
# 1 เดือน = 31 วัน → 2976 จุด
expected_fixed = 96 * 31
print("fixed_expected:", expected_fixed, "missing:", expected_fixed - actual)

In [12]:
df2[df2[['timestamp']].isnull().all(axis=1)]

Empty DataFrame
Columns: [timestamp, dtmsid, C_A, C_B, C_C, F, HC_A, HC_B, HC_C, HV_A, HV_B, HV_C, KWH_A, KWH_B, KWH_C, KWH_FWD, KWH_REV, KWH_TOT, PF_A, PF_B, PF_C, PF_TOT, P_A, P_B, P_C, P_TOT, Q_A, Q_B, Q_C, Q_TOT, S_A, S_B, S_C, S_TOT, TEMP_AMB, TEMP_TR, TEMP_OIL, V_A, V_B, V_C]
Index: []

[0 rows x 40 columns]

In [13]:
df2.isna().sum()

timestamp    0
dtmsid       0
C_A          0
C_B          0
C_C          0
F            0
HC_A         0
HC_B         0
HC_C         0
HV_A         0
HV_B         0
HV_C         0
KWH_A        0
KWH_B        0
KWH_C        0
KWH_FWD      0
KWH_REV      0
KWH_TOT      0
PF_A         0
PF_B         0
PF_C         0
PF_TOT       0
P_A          0
P_B          0
P_C          0
P_TOT        0
Q_A          0
Q_B          0
Q_C          0
Q_TOT        0
S_A          0
S_B          0
S_C          0
S_TOT        0
TEMP_AMB     0
TEMP_TR      0
TEMP_OIL     0
V_A          0
V_B          0
V_C          0
dtype: int64

In [14]:
df2.isnull().sum()

timestamp    0
dtmsid       0
C_A          0
C_B          0
C_C          0
F            0
HC_A         0
HC_B         0
HC_C         0
HV_A         0
HV_B         0
HV_C         0
KWH_A        0
KWH_B        0
KWH_C        0
KWH_FWD      0
KWH_REV      0
KWH_TOT      0
PF_A         0
PF_B         0
PF_C         0
PF_TOT       0
P_A          0
P_B          0
P_C          0
P_TOT        0
Q_A          0
Q_B          0
Q_C          0
Q_TOT        0
S_A          0
S_B          0
S_C          0
S_TOT        0
TEMP_AMB     0
TEMP_TR      0
TEMP_OIL     0
V_A          0
V_B          0
V_C          0
dtype: int64